// Shared constants for analytics pages

// Memory pipeline steps (streamlined agent-forward)
export const STEP_NAME: Record<string, string> = {
  classify: 'Topic Classification',
  classification: 'Query Classification',
  intent_classifier: 'Intent Classifier',
  intent_detection: 'Intent Detection',
  schema_validation: 'Schema & Criteria Validation',
  tool_execution: 'Agent Tool Execution',
  tool_fanout: 'Tool Fan-Out Telemetry',
  agent_coordination: 'Agent Coordination',
  plan_and_select_template: 'Query Planning & Template Selection',
  plan_generation: 'Query Plan Generation',
  planner_agent: 'Planner Agent Lane',
  query_agent: 'Query Agent Lane',
  analyst_agent: 'Analyst Agent Lane',
  chart_agent: 'Chart Agent Lane',
  web_research_agent: 'Web Insights',
  market_agent: 'Market Insights',
  planning: 'Supervisor Planning',
  clarification: 'Requirements Clarification',
  clarification_manager: 'Clarification Manager',
  sql_compilation: 'SQL Compilation',
  sql_validation: 'SQL Validation',
  sql_validator: 'SQL Validator',
  sql_generator: 'SQL Generator',
  sql_executor: 'SQL Executor',
  sql_result_bridge: 'SQL Result Bridge',
  sql_execution: 'Data Retrieval',
  sql_lane: 'SQL Lane',
  market_lane: 'Market Data',
  web_lane: 'Web Research',
  chart_generation: 'Chart Generation',
  chart_designer: 'Chart Designer',
  chart_revision: 'Chart Revision',
  analysis_generation: 'Final Analysis',
  analysis_writer: 'Analysis Writer',
  analysis_revision: 'Analysis Revision',
  web_refresh: 'Web Context Refresh',
  market_refresh: 'Market Data Refresh',
  sql_regeneration: 'SQL Regeneration',
  follow_up_route: 'Follow-Up Guidance',
  finalization: 'Workflow Finalization',
  // Phase 4: *_ready events for lane completion
  sql_ready: 'SQL Complete',
  chart_ready: 'Chart Complete',
  analysis_ready: 'Analysis Complete',
  web_ready: 'Web Research Complete',
  stock_ready: 'Market Data Complete',
  market_ready: 'Market Data Complete',
  workflow_complete: 'Workflow Complete',
  // Phase 3: Specialist pool events
  sql_pool_complete: 'SQL Pool Complete',
  chart_pool_complete: 'Chart Pool Complete',
  analysis_pool_complete: 'Analysis Pool Complete',
  web_pool_complete: 'Web Pool Complete',
  market_pool_complete: 'Market Pool Complete',
  // Error and redirect events
  workflow_error: 'Workflow Error',
  workflow_redirect: 'Workflow Redirect',
};

export const STEP_ORDER = [
  'classify',
  'classification',
  'intent_detection',
  'intent_classifier',
  'schema_validation',
  'clarification',
  'clarification_manager',
  'plan_and_select_template',
  'plan_generation',
  'planner_agent',
  'query_agent',
  'analyst_agent',
  'chart_agent',
  'web_research_agent',
  'market_agent',
  'tool_execution',
  'tool_fanout',
  'agent_coordination',
  'planning',
  'sql_generator',
  'sql_compilation',
  'sql_validator',
  'sql_validation',
  'sql_executor',
  'sql_execution',
  'sql_result_bridge',
  'sql_lane',
  'sql_ready',
  'sql_pool_complete',
  'market_lane',
  'market_ready',
  'stock_ready',
  'market_pool_complete',
  'web_lane',
  'web_refresh',
  'web_ready',
  'web_pool_complete',
  'chart_designer',
  'chart_generation',
  'chart_revision',
  'chart_ready',
  'chart_pool_complete',
  'analysis_writer',
  'analysis_generation',
  'analysis_revision',
  'analysis_ready',
  'analysis_pool_complete',
  'market_refresh',
  'sql_regeneration',
  'follow_up_route',
  'finalization',
  'workflow_error',
  'workflow_redirect',
  'workflow_complete',
];

// SQL pipeline steps (direct workflow)
export const STEP_NAME_SQL: Record<string, string> = {
  classification: 'Query Classification',
  intent_classifier: 'Intent Classifier',
  intent_detection: 'Intent Detection',
  clarification: 'Requirements Clarification',
  clarification_manager: 'Clarification Manager',
  plan_and_select_template: 'Template Selection',
  web_search: 'Market Research',
  schema: 'Schema Analysis',
  schema_validation: 'Schema Validation',
  sql_generator: 'SQL Generator',
  sql_validation: 'SQL Validation',
  sql_validator: 'SQL Validator',
  sql: 'SQL Generation',
  sql_compilation: 'SQL Generation',
  sql_generation: 'SQL Generation',
  table: 'Table Selection',
  table_selection: 'Table Selection',
  sql_executor: 'SQL Executor',
  sql_execution: 'Data Retrieval',
  data_retrieval: 'Data Retrieval',
  sql_result_bridge: 'SQL Result Bridge',
  chart: 'Chart Creation',
  chart_designer: 'Chart Designer',
  chart_generation: 'Chart Creation',
  chart_revision: 'Chart Revision',
  chart_rendering: 'Chart Creation',
  analysis: 'Analysis Generation',
  analysis_generation: 'Analysis Generation',
  analysis_writer: 'Analysis Writer',
  analysis_revision: 'Analysis Revision',
  follow_up_route: 'Follow-Up Guidance',
  workflow_complete: 'Workflow Summary',
  // Lane completion events
  sql_ready: 'SQL Complete',
  chart_ready: 'Chart Complete',
  analysis_ready: 'Analysis Complete',
  web_ready: 'Web Research Complete',
  stock_ready: 'Market Data Complete',
  // Error events
  workflow_error: 'Workflow Error',
  workflow_redirect: 'Workflow Redirect',
};

export const STEP_ORDER_SQL = [
  'classification',
  'intent_classifier',
  'intent_detection',
  'clarification',
  'clarification_manager',
  'plan_and_select_template',
  'web_search',
  'schema',
  'schema_validation',
  'sql_generator',
  'sql_validation',
  'sql_validator',
  'sql',
  'sql_compilation',
  'sql_generation',
  'table',
  'table_selection',
  'sql_executor',
  'sql_execution',
  'sql_result_bridge',
  'sql_ready',
  'data_retrieval',
  'chart',
  'chart_designer',
  'chart_generation',
  'chart_revision',
  'chart_ready',
  'web_ready',
  'stock_ready',
  'analysis',
  'analysis_writer',
  'analysis_generation',
  'analysis_revision',
  'analysis_ready',
  'follow_up_route',
  'workflow_error',
  'workflow_redirect',
  'workflow_complete',
];

