"""Ming Engine agent pipeline: 5 OpenAI Agents SDK agents with structured outputs."""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from typing import Any

from agents import Agent, Runner, RunConfig
from pydantic import BaseModel, Field

try:
    from .calendar_tool import compute_bazi_chart, compute_bazi_chart_tool
    from .classics import retrieve_classical_references, retrieve_classical_references_tool
    from .config import get_settings
    from .bazi_engine import (
        compute_full_analysis, FullBaziAnalysis,
        compute_all_hidden_stems, compute_ten_gods, compute_interactions,
        compute_seasonal_strength, compute_luck_pillars, compute_annual_pillars,
        compute_enhanced_elements, compute_harmony_score, compute_retrodictions,
    )
    from .trace_collector import TraceCollector
except ImportError:
    from calendar_tool import compute_bazi_chart, compute_bazi_chart_tool  # type: ignore[no-redef]
    from classics import retrieve_classical_references, retrieve_classical_references_tool  # type: ignore[no-redef]
    from config import get_settings  # type: ignore[no-redef]
    from bazi_engine import (  # type: ignore[no-redef]
        compute_full_analysis, FullBaziAnalysis,
        compute_all_hidden_stems, compute_ten_gods, compute_interactions,
        compute_seasonal_strength, compute_luck_pillars, compute_annual_pillars,
        compute_enhanced_elements, compute_harmony_score, compute_retrodictions,
    )
    from trace_collector import TraceCollector  # type: ignore[no-redef]


# ---------------------------------------------------------------------------
# Run context
# ---------------------------------------------------------------------------

@dataclass(slots=True)
class FortuneRunContext:
    fortune_id: str
    surface_id: str
    run_id: str | None = None
    question: str | None = None
    focus: str | None = None
    tone: str | None = None
    birth_iso: str = ""
    timezone: str = "UTC"
    birth_time_unknown: bool = False
    gender: str = "unknown"
    metadata: dict[str, Any] = field(default_factory=dict)


def _run_config(ctx: "FortuneRunContext") -> RunConfig:
    """Build RunConfig so TracingProcessor can route spans to the right row.

    OpenAI's hosted tracing exporter requires ``trace_id`` to start with
    ``trace_``; we prepend it here and strip it back to run_id in the
    GlassBoxTraceProcessor resolver. ``group_id`` must start with ``group_``
    for the same reason.
    """
    source_id = ctx.run_id or ctx.fortune_id
    return RunConfig(
        trace_id=f"trace_{source_id.replace('-', '')}" if source_id else None,
        group_id=f"group_{ctx.fortune_id.replace('-', '')}" if ctx.fortune_id else None,
        trace_metadata={
            # OpenAI hosted tracing requires all metadata values to be strings.
            "run_id": ctx.run_id or "",
            "fortune_id": ctx.fortune_id or "",
            "focus": ctx.focus or "",
            "tone": ctx.tone or "",
            "birth_time_unknown": "true" if ctx.birth_time_unknown else "false",
        },
    )


# ---------------------------------------------------------------------------
# Structured output models
# ---------------------------------------------------------------------------

class ElementScore(BaseModel):
    element: str
    score: int


class ElementBalanceOutput(BaseModel):
    scores: list[ElementScore]
    dominant: str
    weakest: str
    summary: str


class ClassicalReference(BaseModel):
    id: str
    passage: str
    translation: str
    source: str
    relevance: str


class InsightBullet(BaseModel):
    """Single bullet point inside an insight section."""
    icon: str = Field(description="Emoji icon for this bullet")
    text: str = Field(description="Concise insight, max ~80 chars")


class InsightSection(BaseModel):
    """One themed card in the accordion (e.g. Strengths, Watch Out)."""
    id: str
    icon: str = Field(description="Section emoji")
    heading: str = Field(description="Short heading, 2-4 words")
    tagline: str = Field(description="1-sentence sub-heading")
    bullets: list[InsightBullet] = Field(min_length=2, max_length=5)
    citations: list[str] = Field(default_factory=list)


class NarrativeOutput(BaseModel):
    """Structured narrative: a TL;DR + 3-4 insight cards."""
    tldr: str = Field(description="1-sentence summary, max 20 words")
    insights: list[InsightSection] = Field(min_length=2, max_length=5)


class YearPrediction(BaseModel):
    """Per-year prediction generated by the narrative agent."""
    year: int
    prediction: str = Field(description="Max 100 chars, key event/theme for this year")
    confidence: float = Field(ge=0.0, le=1.0, description="Confidence based on interaction strength")
    evidence_refs: list[str] = Field(default_factory=list, description="Classical ref IDs or interaction descriptions")


class EnrichedNarrativeOutput(BaseModel):
    """Extended narrative with year predictions and evidence tracking."""
    tldr: str = Field(description="1-sentence summary, max 20 words")
    insights: list[InsightSection] = Field(min_length=2, max_length=5)
    year_predictions: list[YearPrediction] = Field(
        default_factory=list,
        description="Per-year predictions for years with notable interactions",
    )


class FollowUpButton(BaseModel):
    id: str
    label: str


class GuardrailOutput(BaseModel):
    level: str
    message: str
    disclaimer: str
    follow_up_buttons: list[FollowUpButton] = Field(default_factory=list)


DEFAULT_FOLLOW_UP_BUTTONS = [
    FollowUpButton(id="year_forecast", label="Explore This Year Luck"),
    FollowUpButton(id="career_focus", label="Career Deep Dive"),
    FollowUpButton(id="relationship_focus", label="Compatibility Check"),
]


# ---------------------------------------------------------------------------
# Agent instructions
# ---------------------------------------------------------------------------

NARRATIVE_INSTRUCTIONS = """\
You are the Ming Engine narrative interpreter. You have access to a COMPLETE \
deterministic BaZi analysis — Four Pillars, hidden stems (藏干), ten gods (十神), \
branch interactions (冲合害), seasonal strength (旺相休囚死), luck pillars (大运), \
annual pillars (流年), and classical references. Your job is to INTERPRET this \
pre-computed data, not to guess or fabricate BaZi calculations.

Output format:
- tldr: 1 sentence, max 20 words, capturing the core insight.
- insights: 3-4 themed sections. Each section has:
  - id: snake_case identifier (e.g. "core_strength", "dynamics", "advice", "timing")
  - icon: a single emoji that represents the theme (🎯 ⚡ ✨ 🕐 ⚠️ 💡 🔥 🌊)
  - heading: 2-4 word title
  - tagline: 1 sentence explaining the theme for this chart
  - bullets: 2-4 items, each with an emoji icon and short text (max 80 chars, no paragraphs)
  - citations: list of classical reference ids used
- year_predictions: For each year in the annual_pillars that has notable interactions \
  (clashes, combinations, harms), produce a prediction:
  - year: the year number
  - prediction: max 100 chars, the key event or theme
  - confidence: 0.0-1.0 based on how strong the interaction signals are
  - evidence_refs: list of interaction descriptions or classical ref IDs

Guidelines:
- Reference SPECIFIC computed data: "Your 庚 day master scores 3.5 in metal" not "you have strong metal."
- Cite the ten gods by name: "偏印 (Indirect Seal) in month stem signals…"
- Reference interactions explicitly: "寅申冲 (Tiger-Monkey clash) between year and month…"
- Cite classical references by their id.
- Be concise — more insight per word, fewer words per insight.
- For year_predictions, focus on years with clashes or combinations. Skip uneventful years.
- Prefer actionable, practical bullets over abstract philosophy.
"""

GUARDRAIL_INSTRUCTIONS = """\
You are the Ming Engine guardrail layer. Review the narrative for safety and \
generate a user-facing disclaimer with follow-up options.

- Set level to "info" for standard readings, "warning" if the narrative \
touches sensitive topics, "critical" only if content should be suppressed.
- The message is the primary banner text; disclaimer is secondary.
- Canonical follow-up action ids: year_forecast, career_focus, \
relationship_focus, deep_dive_element, show_sources, expand_classics.
- Default button set should NOT include deep_dive_element.
"""


# ---------------------------------------------------------------------------
# Agent definitions
# ---------------------------------------------------------------------------

def _model(setting_name: str) -> str:
    return getattr(get_settings(), setting_name)


INTAKE_AGENT: Agent[FortuneRunContext] = Agent(
    name="fortune_intake",
    model=_model("intake_model"),
    instructions=(
        "Clarify the user intent for a BaZi reading. "
        "Summarize requested focus, tone, and any missing optional details."
    ),
)

CHART_AGENT: Agent[FortuneRunContext] = Agent(
    name="fortune_chart",
    model=_model("chart_model"),
    instructions=(
        "Use the chart tool to compute Four Pillars data. "
        "Explain what the raw element counts imply for downstream interpretation."
    ),
    tools=[compute_bazi_chart_tool],
)

CLASSICS_AGENT: Agent[FortuneRunContext] = Agent(
    name="fortune_classics",
    model=_model("classics_model"),
    instructions=(
        "Use the classics retrieval tool to find concise, relevant textual "
        "support for the current reading focus."
    ),
    tools=[retrieve_classical_references_tool],
)

NARRATIVE_AGENT: Agent[FortuneRunContext] = Agent(
    name="fortune_narrative",
    model=_model("narrative_model"),
    instructions=NARRATIVE_INSTRUCTIONS,
    output_type=EnrichedNarrativeOutput,
)

GUARDRAIL_AGENT: Agent[FortuneRunContext] = Agent(
    name="fortune_guardrail",
    model=_model("guardrail_model"),
    instructions=GUARDRAIL_INSTRUCTIONS,
    output_type=GuardrailOutput,
)


# ---------------------------------------------------------------------------
# Pipeline functions
# ---------------------------------------------------------------------------

def enrich_element_balance(
    raw_counts: dict[str, int],
    day_master_element: str,
) -> ElementBalanceOutput:
    scores = [ElementScore(element=k, score=v) for k, v in raw_counts.items()]
    by_score = sorted(scores, key=lambda s: (-s.score, s.element))
    dominant = by_score[0].element
    weakest = sorted(scores, key=lambda s: (s.score, s.element))[0].element
    return ElementBalanceOutput(
        scores=scores,
        dominant=dominant,
        weakest=weakest,
        summary=(
            f"{dominant.title()} is most prominent, {weakest} is comparatively weak, "
            f"and the day master expresses through {day_master_element}."
        ),
    )


async def run_foundation(ctx: FortuneRunContext) -> dict[str, Any]:
    """Deterministic foundation with traced individual steps.

    Each computation is wrapped in a TraceCollector step so the frontend
    can render a real-time "Glass Box" sidebar showing the THINK -> CALL ->
    RECEIVE -> INTERPRET rhythm.

    Returns foundation dict with an extra "trace" key containing the collector.
    """
    from .bazi_engine import _normalize_dt
    from datetime import datetime as dt

    trace = TraceCollector()

    # 1. Four Pillars chart
    with trace.step("tool_call", "foundation", tool_name="compute_bazi_chart",
                     label="Calculating Four Pillars",
                     input_summary=f"{ctx.birth_iso} tz={ctx.timezone}") as ts:
        chart = compute_bazi_chart(
            ctx.birth_iso, timezone=ctx.timezone,
            birth_time_unknown=ctx.birth_time_unknown,
        )
        ts.output_summary = f"Day Master: {chart['day_master']} ({chart['day_master_element']})"

    # 2. Hidden stems
    with trace.step("tool_call", "foundation", tool_name="compute_hidden_stems",
                     label="Extracting Hidden Stems (\u85cf\u5e72)",
                     input_summary="4 branches") as ts:
        hidden = compute_all_hidden_stems(chart)
        total_hs = sum(len(v) for v in hidden.values())
        ts.output_summary = f"{total_hs} hidden stems across {len(hidden)} pillars"

    # 3. Ten Gods
    with trace.step("tool_call", "foundation", tool_name="compute_ten_gods",
                     label="Classifying Ten Gods (\u5341\u795e)",
                     input_summary=f"Day Master: {chart['day_master']}") as ts:
        ten_gods = compute_ten_gods(chart["day_master"], chart, hidden)
        ts.output_summary = f"{len(ten_gods)} positions classified"

    # 4. Interactions
    with trace.step("tool_call", "foundation", tool_name="compute_interactions",
                     label="Detecting Clashes & Combinations (\u51b2\u5408\u5bb3)",
                     input_summary="checking all branch pairs") as ts:
        interactions = compute_interactions(chart)
        ts.output_summary = f"{len(interactions)} interactions found"

    # 5. Seasonal strength
    month_branch = chart["month"]["branch"] if isinstance(chart["month"], dict) else chart["month"].branch
    with trace.step("tool_call", "foundation", tool_name="compute_seasonal_strength",
                     label="Evaluating Seasonal Strength (\u65fa\u76f8\u4f11\u56da\u6b7b)",
                     input_summary=f"{chart['day_master_element']} in {month_branch}") as ts:
        seasonal = compute_seasonal_strength(chart["day_master_element"], month_branch)
        ts.output_summary = f"{seasonal.strength} (score: {seasonal.score})"

    # 6. Enhanced element counts
    with trace.step("tool_call", "foundation", tool_name="compute_enhanced_elements",
                     label="Weighting Element Balance",
                     input_summary="stems + hidden stems") as ts:
        enhanced_counts, element_by_source = compute_enhanced_elements(chart, hidden)
        dominant = max(enhanced_counts, key=enhanced_counts.get)  # type: ignore[arg-type]
        ts.output_summary = f"Dominant: {dominant} ({enhanced_counts[dominant]:.1f})"

    # 7. Luck pillars
    luck_pillars = []
    if ctx.gender.lower() not in ("unknown", ""):
        with trace.step("tool_call", "foundation", tool_name="compute_luck_pillars",
                         label="Computing Luck Pillars (\u5927\u8fd0)",
                         input_summary=f"gender={ctx.gender}") as ts:
            luck_pillars = compute_luck_pillars(chart, ctx.birth_iso, ctx.timezone, ctx.gender)
            ts.output_summary = f"{len(luck_pillars)} decades computed"

    # 8. Annual pillars
    local_dt = _normalize_dt(ctx.birth_iso, ctx.timezone)
    birth_year = local_dt.year
    current_year = dt.now().year
    with trace.step("tool_call", "foundation", tool_name="compute_annual_pillars",
                     label="Computing Annual Pillars (\u6d41\u5e74)",
                     input_summary=f"{birth_year}-{current_year + 10}") as ts:
        annual_pillars = compute_annual_pillars(birth_year, current_year + 10, chart, luck_pillars)
        notable = sum(1 for ap in annual_pillars if ap.interactions_with_chart)
        ts.output_summary = f"{len(annual_pillars)} years, {notable} with interactions"

    # 9. Retrodictions (Spooky Accuracy)
    with trace.step("tool_call", "foundation", tool_name="compute_retrodictions",
                     label="Generating Retrodictions (Spooky Accuracy)",
                     input_summary=f"scanning past years for strong interactions") as ts:
        retrodictions = compute_retrodictions(annual_pillars, current_year=current_year)
        ts.output_summary = f"{len(retrodictions)} retrodictions generated"

    # 10. Harmony score
    harmony = compute_harmony_score(interactions)

    # Build FullBaziAnalysis for downstream compatibility
    analysis = FullBaziAnalysis(
        pillars=chart,
        hidden_stems=hidden,
        ten_gods=ten_gods,
        interactions=interactions,
        seasonal_strength=seasonal,
        luck_pillars=luck_pillars,
        annual_pillars=annual_pillars,
        enhanced_element_counts=enhanced_counts,
        element_by_source=element_by_source,
        harmony_score=harmony,
    )

    # 10. Element balance (legacy)
    elements = enrich_element_balance(
        chart["raw_element_counts"],
        chart["day_master_element"],
    )

    # 11. Classical retrieval
    with trace.step("tool_call", "foundation", tool_name="retrieve_classical_references",
                     label="Consulting Classical Texts",
                     input_summary=f"query: {ctx.focus or 'general'}") as ts:
        query_parts = [ctx.question, ctx.focus, ctx.tone, chart["day_master_element"]]
        retrieval_query = " ".join(p for p in query_parts if p) or "general bazi reading"
        references = [
            ClassicalReference(**item)
            for item in retrieve_classical_references(retrieval_query)
        ]
        ts.output_summary = f"{len(references)} passages matched"

    return {
        "pillars": chart,
        "elements": elements,
        "references": references,
        "analysis": analysis,
        "retrodictions": retrodictions,
        "trace": trace,
    }


def _build_narrative_prompt(ctx: FortuneRunContext, foundation: dict[str, Any]) -> str:
    """Build the JSON prompt for the narrative agent with full analysis data."""
    analysis: FullBaziAnalysis = foundation["analysis"]

    # Include enriched data — the narrative agent interprets pre-computed results
    prompt_data: dict[str, Any] = {
        "focus": ctx.focus,
        "tone": ctx.tone,
        "question": ctx.question,
        "pillars": foundation["pillars"],
        "elements": foundation["elements"].model_dump(),
        "references": [r.model_dump() for r in foundation["references"]],
        # Enriched computation data
        "hidden_stems": {k: [s.model_dump() for s in v] for k, v in analysis.hidden_stems.items()},
        "ten_gods": [tg.model_dump() for tg in analysis.ten_gods],
        "interactions": [ix.model_dump() for ix in analysis.interactions],
        "seasonal_strength": analysis.seasonal_strength.model_dump(),
        "enhanced_element_counts": analysis.enhanced_element_counts,
        "harmony_score": analysis.harmony_score,
    }

    # Include luck + annual pillars if available (for year predictions)
    if analysis.luck_pillars:
        prompt_data["luck_pillars"] = [lp.model_dump() for lp in analysis.luck_pillars[:4]]  # current + next 3
    if analysis.annual_pillars:
        # Only include years with interactions (to keep prompt size reasonable)
        notable_years = [
            ap.model_dump() for ap in analysis.annual_pillars
            if ap.interactions_with_chart
        ]
        prompt_data["notable_annual_pillars"] = notable_years[:20]  # cap at 20

    return json.dumps(prompt_data, ensure_ascii=False)


async def run_narrative(
    ctx: FortuneRunContext,
    *,
    foundation: dict[str, Any],
) -> EnrichedNarrativeOutput:
    """Run the narrative agent (non-streaming) and return structured output."""
    prompt = _build_narrative_prompt(ctx, foundation)
    result = await Runner.run(
        NARRATIVE_AGENT,
        input=prompt,
        context=ctx,
        run_config=_run_config(ctx),
    )
    if isinstance(result.final_output, EnrichedNarrativeOutput):
        return result.final_output
    return EnrichedNarrativeOutput.model_validate(result.final_output)


async def run_narrative_streamed(
    ctx: FortuneRunContext,
    *,
    foundation: dict[str, Any],
):
    """Run the narrative agent with streaming. Returns the streamed run result."""
    prompt = _build_narrative_prompt(ctx, foundation)
    return Runner.run_streamed(
        NARRATIVE_AGENT,
        input=prompt,
        context=ctx,
        run_config=_run_config(ctx),
    )


async def run_guardrail(
    ctx: FortuneRunContext,
    *,
    narrative: NarrativeOutput,
) -> GuardrailOutput:
    """Run the guardrail agent and return structured output."""
    prompt = json.dumps(
        {
            "focus": ctx.focus,
            "tone": ctx.tone,
            "insights": [s.model_dump() for s in narrative.insights],
            "default_buttons": [b.model_dump() for b in DEFAULT_FOLLOW_UP_BUTTONS],
        },
        ensure_ascii=False,
    )
    result = await Runner.run(
        GUARDRAIL_AGENT,
        input=prompt,
        context=ctx,
        run_config=_run_config(ctx),
    )
    if isinstance(result.final_output, GuardrailOutput):
        return result.final_output
    return GuardrailOutput.model_validate(result.final_output)
