# --- Analytics Function/Class Map ---
#   (No top-level functions or classes in this module.)
# --- End Analytics Function/Class Map ---
from .fanout import (
    TOOL_QUEUE_SENTINEL,
    ToolParallelRuntime,
    derive_accessory_events,
    start_tool_parallelism,
)
from .sql_lane import (
    _cached_event,
    compose_chart_ready_payload,
    compose_sql_ready_payload,
    compose_stock_ready_payload,
    compose_web_ready_payload,
    limit_sample_rows,
    stream_chart_lane,
    stream_sql_lane,
)
from .analysis_lane import (
    ensure_analysis_dependencies,
    stream_analysis_lane,
)
from .orchestration import (
    maybe_emit_fresh_lane_event,
    collect_tool_deltas_now,
    drain_tool_state_async,
)
from .revision import (
    REVISION_EVENT_ALIASES,
    annotate_revision_event,
    build_revision_request_event,
    build_revision_plan,
    apply_revision_plan,
    derive_revision_targets,
    mark_revision_completion,
    normalize_revision_targets,
)
from .stage_helpers import (
    hash_payload,
    normalize_metric_slots,
    build_slot_assumptions,
    ensure_tool_receipt,
    _safe_year,
    _safe_date,
    _summarize_sql_rows,
    _extract_tldr,
    _extract_bullets,
    _split_line,
    _normalize_sentence,
    _collect_sentences,
    _extract_key_numbers,
    _extract_risk_watch,
    _extract_next_steps,
    _evaluate_latency_guardrail,
    _build_evidence_entries,
    # Snapshot helpers (moved from planner_executor.py)
    SNAPSHOT_MAX_AGE_SECONDS,
    _artifacts_from_snapshot,
    _dataset_preview_from_snapshot,
    _snapshot_age_seconds_from_snapshot,
    _is_snapshot_fresh,
)
from .intent_stage import (
    run_classification_stage,
    run_intent_stage,
    _apply_plan_metric_defaults,
    _apply_plan_timeframe_defaults,
    _build_schema_clarifier_request,
    _followup_to_clarify_request,
    _clarify_request_to_followup,
    _filter_answered_requests,
    _refresh_followups,
    _upsert_slot_status,
    _compose_intent_from_resolution,
    SCHEMA_CLARIFIER_ENABLED,
)
from .clarification_stage import (
    run_clarification_stage,
    _auto_fill_missing_slots,
)
from .sql_stage import (
    run_sql_stage,
    run_sql_pipeline_stage,
    _normalize_calendar_filters,
    _set_sql_generation_artifact,
    _set_sql_execution_artifact,
)
from .chart_stage import run_chart_stage, run_chart_pipeline_stage
from .analysis_stage import run_analysis_stage

__all__ = [
    "TOOL_QUEUE_SENTINEL",
    "ToolParallelRuntime",
    "derive_accessory_events",
    "start_tool_parallelism",
    "_cached_event",
    "compose_chart_ready_payload",
    "compose_sql_ready_payload",
    "compose_stock_ready_payload",
    "compose_web_ready_payload",
    "limit_sample_rows",
    "stream_chart_lane",
    "stream_sql_lane",
    "ensure_analysis_dependencies",
    "stream_analysis_lane",
    "REVISION_EVENT_ALIASES",
    "annotate_revision_event",
    "build_revision_request_event",
    "build_revision_plan",
    "apply_revision_plan",
    "derive_revision_targets",
    "mark_revision_completion",
    "normalize_revision_targets",
    "hash_payload",
    "normalize_metric_slots",
    "build_slot_assumptions",
    "ensure_tool_receipt",
    "_safe_year",
    "_safe_date",
    "_summarize_sql_rows",
    "_extract_tldr",
    "_extract_bullets",
    "_split_line",
    "_normalize_sentence",
    "_collect_sentences",
    "_extract_key_numbers",
    "_extract_risk_watch",
    "_extract_next_steps",
    "_evaluate_latency_guardrail",
    "_build_evidence_entries",
    # Snapshot helpers
    "SNAPSHOT_MAX_AGE_SECONDS",
    "_artifacts_from_snapshot",
    "_dataset_preview_from_snapshot",
    "_snapshot_age_seconds_from_snapshot",
    "_is_snapshot_fresh",
    "run_classification_stage",
    "run_intent_stage",
    "_apply_plan_metric_defaults",
    "_apply_plan_timeframe_defaults",
    "_build_schema_clarifier_request",
    "_followup_to_clarify_request",
    "_clarify_request_to_followup",
    "_filter_answered_requests",
    "_refresh_followups",
    "_upsert_slot_status",
    "_compose_intent_from_resolution",
    "SCHEMA_CLARIFIER_ENABLED",
    "run_clarification_stage",
    "_auto_fill_missing_slots",
    "run_sql_stage",
    "run_sql_pipeline_stage",
    "_normalize_calendar_filters",
    "_set_sql_generation_artifact",
    "_set_sql_execution_artifact",
    "run_chart_stage",
    "run_chart_pipeline_stage",
    "run_analysis_stage",
    "maybe_emit_fresh_lane_event",
    "collect_tool_deltas_now",
    "drain_tool_state_async",
]
